BaCore.h File Reference
OS level API.
#include `BaBool.h`
*
#include <unistd.h>
*
Classes
struct TBaCoreTimeStamp
Time stamp structure.
struct TBaCoreThreadArg
Thread function arguments.
struct TBaCoreThreadInfo
Thread info.
Typedefs
typedef struct TBaCoreTimeStamp TBaCoreTimeStamp
Time stamp structure.
typedef enum EBaCorePrio EBaCorePrio
Thread priority and scheduler. RT is FIFO.
typedef struct TBaCoreThreadArg TBaCoreThreadArg
Thread function arguments.
typedef struct TBaCoreThreadInfo TBaCoreThreadInfo
Thread info.
typedef void(* TBaCoreFun) (void *arg)
General function of the API.
typedef void(* TBaCoreThreadFun) (TBaCoreThreadArg *pArg)
Functions for threads.
typedef const void * TBaCoreThreadHdl
Thread handle.
Enumerations
enum EBaCorePrio {
*
eBaCorePrio_Minimum = 0,
eBaCorePrio_Low,
eBaCorePrio_Normal,
eBaCorePrio_High,
*
eBaCorePrio_Highest,
eBaCorePrio_RT_Normal,
eBaCorePrio_RT_High,
eBaCorePrio_RT_Highest
 }
Thread priority and scheduler. RT is FIFO.
Functions
Sleep functions
void BaCoreSleep (int64_t s)
Puts the thread to sleep and causes context change.
void BaCoreMSleep (int64_t ms)
Puts the thread to sleep and causes context change.
void BaCoreUSleep (int64_t us)
Puts the thread to sleep and causes context change.
void BaCoreNSleep (int64_t ns)
Puts the thread to sleep and causes context change.
Timing functions
int64_t BaCoreTimedS (TBaCoreFun fun, void *pArg)
Timing function.
int64_t BaCoreTimedMs (TBaCoreFun fun, void *pArg)
Timing function.
int64_t BaCoreTimedUs (TBaCoreFun fun, void *pArg)
Timing function.
void BaCoreGetTStamp (TBaCoreTimeStamp *pStamp)
Gets the actual time timestamp.
const char * BaCoreTStampToStr (const TBaCoreTimeStamp *pStamp)
Converts time stamp structure to mallocated string.
Multi-threading
TBaCoreThreadHdl BaCoreCreateThread (const char *name, TBaCoreThreadFun routine, TBaCoreThreadArg *pArg, EBaCorePrio prio)
Thread factory.
TBaBoolRC BaCoreDestroyThread (TBaCoreThreadHdl hdl, uint32_t timeOutMs)
Thread destructor.
TBaBoolRC BaCoreGetThreadInfo (const TBaCoreThreadHdl hdl, TBaCoreThreadInfo *pInfo)
Get the thread info.
Other getter setters
TBaBoolRC BaCoreSetOwnProcPrio (EBaCorePrio prio)
Set the priority of the calling process.
EBaCorePrio BaCoreGetOwnProcPrio ()
Get the priority of the calling process.
const char * BaCoreGetOwnName ()
Gets the name of the calling process.
PID Files
pid_t BaCoreReadPidFile (const char *progName, TBaBool internal)
Tries to read the PID from an internal program, or from a path.
TBaBoolRC BaCoreTestPidFile (const char *progName)
TODO: Checks if the internal program is running.
TBaBoolRC BaCoreWritePidFile (const char *progName)
Writes the PID file of an internal program.
TBaBoolRC BaCoreRemovePidFile (const char *progName)
Remover the PID file of an internal program.
Detailed Description
OS level API.
Core functions include:
Timers
Threads
Sleeps
Enumeration Type Documentation
enum EBaCorePrio
Thread priority and scheduler. RT is FIFO.
Enumerator
eBaCorePrio_Minimum
 0
eBaCorePrio_Low
 1
eBaCorePrio_Normal
 2
eBaCorePrio_High
 3
eBaCorePrio_Highest
 4
eBaCorePrio_RT_Normal
 5
eBaCorePrio_RT_High
 6
eBaCorePrio_RT_Highest
 7
Function Documentation
void BaCoreSleep (int64_t s)
Puts the thread to sleep and causes context change.
if s = 0 || ms = 0 || us = 0, there is no sleep if ns = 0, the thread sleeps for one tick as specified by nanosleep()
Parameters
in s Sleep time in s
void BaCoreMSleep (int64_t ms)
Puts the thread to sleep and causes context change.
if s = 0 || ms = 0 || us = 0, there is no sleep if ns = 0, the thread sleeps for one tick as specified by nanosleep()
Parameters
in ms Sleep time in ms
void BaCoreUSleep (int64_t us)
Puts the thread to sleep and causes context change.
if s = 0 || ms = 0 || us = 0, there is no sleep if ns = 0, the thread sleeps for one tick as specified by nanosleep()
Parameters
in us Sleep time in us
Referenced by BaApiStartCtrlTask(), and BaGpioSetClkHWPWM().
void BaCoreNSleep (int64_t ns)
Puts the thread to sleep and causes context change.
if s = 0 || ms = 0 || us = 0, there is no sleep if ns = 0, the thread sleeps for one tick as specified by nanosleep()
Parameters
in ns Sleep time in ns
int64_t BaCoreTimedS (TBaCoreFun fun, void * pArg)
Timing function.
Returns
Time in the defined unit
Parameters
in fun Function to be timed
in pArg Function arguments
int64_t BaCoreTimedMs (TBaCoreFun fun, void * pArg)
Timing function.
Returns
Time in the defined unit
Parameters
in fun Function to be timed
in pArg Function arguments
int64_t BaCoreTimedUs (TBaCoreFun fun, void * pArg)
Timing function.
Returns
Time in the defined unit
Parameters
in fun Function to be timed
in pArg Function arguments
Referenced by BaApiStartCtrlTask().
void BaCoreGetTStamp (TBaCoreTimeStamp * pStamp)
Gets the actual time timestamp.
Parameters
out pStamp Time stamp or null if error
const char* BaCoreTStampToStr (const TBaCoreTimeStamp * pStamp)
Converts time stamp structure to mallocated string.
The user must free the returned pointer to avoid memory leaks
Returns
Time stamp string if success, otherwise, null
Parameters
in pStamp Time stamp to convert to string
TBaCoreThreadHdl BaCoreCreateThread (const char * name, TBaCoreThreadFun routine, TBaCoreThreadArg * pArg, EBaCorePrio prio)
Thread factory.
Returns
Thread handle
Parameters
in name Thread name
in routine Thread entry function
in pArg Arguments of thread function
in prio Thread priority
Referenced by BaApiStartCtrlThread(), and BaGpioStartSWPWM().
TBaBoolRC BaCoreDestroyThread (TBaCoreThreadHdl hdl, uint32_t timeOutMs)
Thread destructor.
It signals the thread to end and waits a maximum of timeOutMs ms. If it timeouts, the thread detaches, stays alive, and releases the resources when the thread routine returns.
Returns
Error if bad handle, or success
Parameters
in hdl Thread handle
in timeOutMs Timeout to wait in ms.
Referenced by BaApiStopCtrlThread(), and BaGpioStopSWPWM().
TBaBoolRC BaCoreGetThreadInfo (const TBaCoreThreadHdl hdl, TBaCoreThreadInfo * pInfo)
Get the thread info.
Returns
Error or success
Parameters
in hdl Thread handle
out pInfo Thread info
TBaBoolRC BaCoreSetOwnProcPrio (EBaCorePrio prio)
Set the priority of the calling process.
TODO: unit test
Returns
Error or success
Parameters
in prio New priority
Referenced by BaApiStartCtrlTask().
EBaCorePrio BaCoreGetOwnProcPrio ()
Get the priority of the calling process.
TODO: unit test
Returns
the priority
const char* BaCoreGetOwnName ()
Gets the name of the calling process.
Mangling with the returned pointer leads to undefined behavior, please do not mess with it
Returns
The name of the calling process
pid_t BaCoreReadPidFile (const char * progName, TBaBool internal)
Tries to read the PID from an internal program, or from a path.
Returns
on success, the PID, otherwise, -1
Parameters
in progName Internal program name or path to PID file
in internal Flag to signal that the program was created with this API
Referenced by BaApiStopCtrlTask(), and BaCoreTestPidFile().
TBaBoolRC BaCoreTestPidFile (const char * progName)
TODO: Checks if the internal program is running.
Returns
Success or error
Referenced by BaApiStartCtrlTask().
TBaBoolRC BaCoreWritePidFile (const char * progName)
Writes the PID file of an internal program.
The own name can be read with BaCoreGetOwnName().
Returns
Success or error
Parameters
in progName Internal program name
Referenced by BaApiStartCtrlTask().
TBaBoolRC BaCoreRemovePidFile (const char * progName)
Remover the PID file of an internal program.
The own name can be read with BaCoreGetOwnName().
Returns
Success or error
Parameters
in progName Internal program name
Referenced by BaApiStartCtrlTask().