BaGpio.h File Reference
GPIOs APIs.
#include `BaBool.h`
*
Classes
class IBaGpio
C++ interface This is a C++ wrapper of the C API above adding multi process safety and a few extra functions.
Typedefs
typedef uint8_t TBaGpio
GPIOs range from 1 to 27.
typedef void * TBaGpioSWPWMHdl
Software PWM handle.
typedef enum EBaGpioHWPWMMode EBaGpioHWPWMMode
HW PWM mode flag.
Enumerations
Functions
Init/Exit Functions
TBaBoolRC BaGpioInit ()
Initializes and frees resources.
TBaBoolRC BaGpioExit ()
Initializes and frees resources.
Hardware PWM setup functions
TBaBoolRC BaGpioInitHWPWM ()
Initialize the hardware PWM functionality with default frequency 1000 Hz and resolution 256 steps.
TBaBoolRC BaGpioExitHWPWM ()
Exit and release resources of the hardware PWM functionality.
TBaBoolRC BaGpioSetClkHWPWM (double frequency, uint32_t resolution, EBaGpioHWPWMMode mode)
Set the frequency and resolution of the hardware PWM.
Basic GPIO operations
TBaBoolRC BaGpioCleanUp (TBaGpio gpio)
Cleans up the GPIO and leaves it on default state.
TBaBoolRC BaGpioSetInp (TBaGpio gpio)
Sets GPIO as input.
TBaBoolRC BaGpioSetOut (TBaGpio gpio)
Sets GPIO as output.
TBaBoolRC BaGpioSetAlt (TBaGpio gpio, int alt)
Sets GPIO as alternative function.
TBaBoolRC BaGpioSet (TBaGpio gpio)
Sets GPIO high.
TBaBoolRC BaGpioReset (TBaGpio gpio)
Sets GPIO low.
TBaBool BaGpioGet (TBaGpio gpio)
Gets the GPIO state high/low.
PWM Functions
TBaBoolRC BaGpioStartHWPWM (TBaGpio gpio, float dutyCycle)
Start the hardware PWM.
TBaBoolRC BaGpioResetHWPWMDuCy (TBaGpio gpio, float dutyCycle)
Reset the duty cycle of the hardware PWM.
TBaBoolRC BaGpioStopHWPWM (TBaGpio gpio)
Stop the hardware PWM.
TBaGpioSWPWMHdl BaGpioStartSWPWM (TBaGpio gpio, float dutyC, uint16_t periodMs)
Start software PWM on the desired GPIO with normal soft real-time priority.
TBaBoolRC BaGpioResetSWPWMDuCy (TBaGpioSWPWMHdl hdl, float dutyC)
Reset the duty cycle of the software PWM.
TBaBoolRC BaGpioStopSWPWM (TBaGpioSWPWMHdl hdl)
Stop the software PWM.
C-Linkage object oriented factory
IBaGpio * IBaGpioCreate (TBaGpio gpio)
C++ interface object oriented factory.
TBaBoolRC IBaGpioDelete (IBaGpio *pHdl)
C++ interface object oriented destructor.
Detailed Description
GPIOs APIs.
C API:
The C API is thread-safe unless explicitly specified otherwise.
The C API has an initializations counter. Do not call the BaGpioExit() function without having called BaGpioInit() first.
The C API is not multi-process safe. Processes can overwrite each other
C++ API
The object oriented C++ API is multiprocess safe between processes using this API
Enumeration Type Documentation
enum EBaGpioHWPWMMode
HW PWM mode flag.
Enumerator
EBaGpioHWPWMMode_MarkedSpace
 Traditional PWM mode.
EBaGpioHWPWMMode_Balanced
 Default mode.
Function Documentation
TBaBoolRC BaGpioInit ()
Initializes and frees resources.
Returns
Error or success
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioExit ()
Initializes and frees resources.
Returns
Error or success
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioInitHWPWM ()
Initialize the hardware PWM functionality with default frequency 1000 Hz and resolution 256 steps.
WARNING: The RPI uses the PWM subsystem to produce audio. As such please refrain from playing audio on the RPI while this code is running
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioExitHWPWM ()
Exit and release resources of the hardware PWM functionality.
Returns
Error or success
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioSetClkHWPWM (double frequency, uint32_t resolution, EBaGpioHWPWMMode mode)
Set the frequency and resolution of the hardware PWM.
The clock frequency is 19.2 MHz The maximum resolution is 4095 steps (12-bit) Please choose these wisely and bare in mind that the actual frequency is an estimate because only positive clock frequency divisors can be used. freq_max @ min resolution (1-step) is 9.6 MHz freq_max @ max resolution (12-bit) is 2.34 kHz Examples: freq_max @ 1024-steps (10-bit) is 9.375 kHz freq_max @ 256-steps (8-bit) is 37.5 kHz Conditions: frequency * resolution * 2 < 19.2 MHz resolution <= 4095
Returns
Error or success
Parameters
in frequency desired frequency in Hz
in resolution desired resolution in steps
in mode PWM mode
Referenced by BaGpioInitHWPWM(), and BaGpioStopSWPWM().
TBaBoolRC BaGpioCleanUp (TBaGpio gpio)
Cleans up the GPIO and leaves it on default state.
Returns
Error or success
Parameters
in gpio GPIO number
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioSetInp (TBaGpio gpio)
Sets GPIO as input.
Returns
Error or success
Parameters
in gpio GPIO number
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioSetOut (TBaGpio gpio)
Sets GPIO as output.
Returns
Error or success
Parameters
in gpio GPIO number
Referenced by BaGpioStartSWPWM(), and BaGpioStopSWPWM().
TBaBoolRC BaGpioSetAlt (TBaGpio gpio, int alt)
Sets GPIO as alternative function.
Returns
Error or success
Parameters
in gpio GPIO number
in alt Alternative function of GPIO
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioSet (TBaGpio gpio)
Sets GPIO high.
Not thread safe for performance reasons
Returns
Error or success
Parameters
in gpio GPIO number
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioReset (TBaGpio gpio)
Sets GPIO low.
Not thread safe for performance reasons
Returns
Error or success
Parameters
in gpio GPIO number
Referenced by BaGpioStopSWPWM().
TBaBool BaGpioGet (TBaGpio gpio)
Gets the GPIO state high/low.
Returns
high true, or low false
Parameters
in gpio GPIO number
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioStartHWPWM (TBaGpio gpio, float dutyCycle)
Start the hardware PWM.
The BaGpioInitHWPWM() function must be called before starting the HW PWM. Only GPIOs 12, 13, 18, and 19 can be rerouted to the PWM.
Returns
Error or success
Parameters
in gpio GPIO number
in dutyCycle Desired duty cycle [0..1]
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioResetHWPWMDuCy (TBaGpio gpio, float dutyCycle)
Reset the duty cycle of the hardware PWM.
BaGpioStartHWPWM() must be called before reseting the duty cycle. Not thread safe for performance reasons.
Returns
Error or success
Parameters
in gpio GPIO number
in dutyCycle Desired duty cycle [0..1]
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioStopHWPWM (TBaGpio gpio)
Stop the hardware PWM.
Returns
Error or success
Parameters
in gpio GPIO number
Referenced by BaGpioStopSWPWM().
TBaGpioSWPWMHdl BaGpioStartSWPWM (TBaGpio gpio, float dutyC, uint16_t periodMs)
Start software PWM on the desired GPIO with normal soft real-time priority.
The period must between 10 and 10000 ms. Input outside range will be limited. The faster the period, the more CPU usage.
Returns
The software PWM handle if success, otherwise, null
Parameters
in gpio Desired GPIO
in dutyC Initial duty cycle [0..1]
in periodMs PWM period in ms [10..10000]
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioResetSWPWMDuCy (TBaGpioSWPWMHdl hdl, float dutyC)
Reset the duty cycle of the software PWM.
Returns
Error or success
Parameters
in hdl Software PWM handle
in dutyC Desired duty cycle [0..1]
Referenced by BaGpioStopSWPWM().
TBaBoolRC BaGpioStopSWPWM (TBaGpioSWPWMHdl hdl)
Stop the software PWM.
Returns
Error or success
Parameters
in hdl Software PWM handle
IBaGpio* IBaGpioCreate (TBaGpio gpio)
C++ interface object oriented factory.
Returns
Pointer to C++ interface if success, otherwise, error
Parameters
in gpio GPIO number
TBaBoolRC IBaGpioDelete (IBaGpio * pHdl)
C++ interface object oriented destructor.
Returns
Error or success
Parameters
in pHdl Interface handle