BaLog.h File Reference
...
#include `BaBool.h`
*
Classes
struct TBaLogOptions
Logger options.
class IBaLog
Logger C++ interface.
Typedefs
typedef enum EBaLogPrio EBaLogPrio
Message priority or severeness.
typedef enum EBaLogOut EBaLogOut
Logger output enumeration.
typedef struct TBaLogOptions TBaLogOptions
Logger options.
typedef void * TBaLogHdl
C logger handle.
Enumerations
Functions
TBaLogHdl BaLogCreateDef (const char *name)
Create factory for a logger with defaults.
TBaLogHdl BaLogCreate (TBaLogOptions *pOpts)
Create factory for a logger.
TBaBoolRC BaLogDestroy (TBaLogHdl hdl, TBaBool saveCfg)
Destroy and release resources of logger.
IBaLog * CBaLogCreateDef (const char *name)
Create factory for a logger with defaults.
IBaLog * CBaLogCreate (TBaLogOptions *pOpts)
Create factory for a logger.
TBaBoolRC CBaLogDestroy (IBaLog *pHdl, TBaBool saveCfg)
Destroy and release resources of logger.
Logging functions
TBaBoolRC BaLogLog (TBaLogHdl hdl, EBaLogPrio prio, const char *tag, const char *msg)
Logs a message into the logger and adds a tag and a time stamp.
TBaBoolRC BaLogTrace (TBaLogHdl hdl, const char *tag, const char *msg)
Logs a message into the logger and adds a tag and a time stamp.
TBaBoolRC BaLogWarning (TBaLogHdl hdl, const char *tag, const char *msg)
Logs a message into the logger and adds a tag and a time stamp.
TBaBoolRC BaLogError (TBaLogHdl hdl, const char *tag, const char *msg)
Logs a message into the logger and adds a tag and a time stamp.
Logging functions with format
TBaBoolRC BaLogLogF (TBaLogHdl *pHdl, EBaLogPrio prio, const char *tag, const char *fmt,...)
Logs a message into the logger like printf() and adds a tag and a time stamp.
TBaBoolRC BaLogTraceF (TBaLogHdl *pHdl, const char *tag, const char *fmt,...)
Logs a message into the logger like printf() and adds a tag and a time stamp.
TBaBoolRC BaLogWarningF (TBaLogHdl *pHdl, const char *tag, const char *fmt,...)
Logs a message into the logger like printf() and adds a tag and a time stamp.
TBaBoolRC BaLogErrorF (TBaLogHdl *pHdl, const char *tag, const char *fmt,...)
Logs a message into the logger like printf() and adds a tag and a time stamp.
Detailed Description
...
Enumeration Type Documentation
enum EBaLogPrio
Message priority or severeness.
Enumerator
eBaLogPrio_Trace
 0
eBaLogPrio_Warning
 1
eBaLogPrio_Error
 2
eBaLogPrio_UpsCrash
 3
enum EBaLogOut
Logger output enumeration.
Enumerator
eBaLogOut_Log
 1
eBaLogOut_Console
 2
eBaLogOut_LogAndConsole
 3
Function Documentation
TBaLogHdl BaLogCreateDef (const char * name)
Create factory for a logger with defaults.
Returns
Handle if success, otherwise, null
Parameters
in name Name of the logger
TBaLogHdl BaLogCreate (TBaLogOptions * pOpts)
Create factory for a logger.
Returns
Handle if success, otherwise, null
Parameters
in pOpts Logger options
TBaBoolRC BaLogDestroy (TBaLogHdl hdl, TBaBool saveCfg)
Destroy and release resources of logger.
Returns
True if success, otherwise, false
Parameters
in hdl BaLog handle to destroy
in saveCfg Flag to specify if the state should be saved in a cfg file
TBaBoolRC BaLogLog (TBaLogHdl hdl, EBaLogPrio prio, const char * tag, const char * msg)
Logs a message into the logger and adds a tag and a time stamp.
The Trace() and rest functions have an implied priority
Returns
true if success, otherwise, false
Parameters
in hdl Handle
in prio Message priority
in tag Optional tag of maximum 6 chars + 7th terminating null
in msg Message to log
TBaBoolRC BaLogTrace (TBaLogHdl hdl, const char * tag, const char * msg)
Logs a message into the logger and adds a tag and a time stamp.
The Trace() and rest functions have an implied priority
Returns
true if success, otherwise, false
Parameters
in hdl Handle
in tag Optional tag of maximum 6 chars + 7th terminating null
in msg Message to log
TBaBoolRC BaLogWarning (TBaLogHdl hdl, const char * tag, const char * msg)
Logs a message into the logger and adds a tag and a time stamp.
The Trace() and rest functions have an implied priority
Returns
true if success, otherwise, false
Parameters
in hdl Handle
in tag Optional tag of maximum 6 chars + 7th terminating null
in msg Message to log
TBaBoolRC BaLogError (TBaLogHdl hdl, const char * tag, const char * msg)
Logs a message into the logger and adds a tag and a time stamp.
The Trace() and rest functions have an implied priority
Returns
true if success, otherwise, false
Parameters
in hdl Handle
in tag Optional tag of maximum 6 chars + 7th terminating null
in msg Message to log
TBaBoolRC BaLogLogF (TBaLogHdl * pHdl, EBaLogPrio prio, const char * tag, const char * fmt, ...)
Logs a message into the logger like printf() and adds a tag and a time stamp.
These functions have a limit of 65534 characters per message. The TraceF() and rest functions have an implied priority
Returns
true if success, otherwise, false
Parameters
in pHdl Handle
in prio Message priority
in tag Optional tag of maximum 6 chars + 7th terminating null
in fmt Message format
Referenced by BaLogError().
TBaBoolRC BaLogTraceF (TBaLogHdl * pHdl, const char * tag, const char * fmt, ...)
Logs a message into the logger like printf() and adds a tag and a time stamp.
These functions have a limit of 65534 characters per message. The TraceF() and rest functions have an implied priority
Returns
true if success, otherwise, false
Parameters
in pHdl Handle
in tag Optional tag of maximum 6 chars + 7th terminating null
in fmt Message format
Referenced by BaLogError().
TBaBoolRC BaLogWarningF (TBaLogHdl * pHdl, const char * tag, const char * fmt, ...)
Logs a message into the logger like printf() and adds a tag and a time stamp.
These functions have a limit of 65534 characters per message. The TraceF() and rest functions have an implied priority
Returns
true if success, otherwise, false
Parameters
in pHdl Handle
in tag Optional tag of maximum 6 chars + 7th terminating null
in fmt Message format
Referenced by BaLogError().
TBaBoolRC BaLogErrorF (TBaLogHdl * pHdl, const char * tag, const char * fmt, ...)
Logs a message into the logger like printf() and adds a tag and a time stamp.
These functions have a limit of 65534 characters per message. The TraceF() and rest functions have an implied priority
Returns
true if success, otherwise, false
Parameters
in pHdl Handle
in tag Optional tag of maximum 6 chars + 7th terminating null
in fmt Message format
Referenced by BaLogError().
IBaLog* CBaLogCreateDef (const char * name)
Create factory for a logger with defaults.
Returns
Handle if success, otherwise, null
Parameters
in name Name of the logger
IBaLog* CBaLogCreate (TBaLogOptions * pOpts)
Create factory for a logger.
Returns
Handle if success, otherwise, null
Parameters
in pOpts Logger options
TBaBoolRC CBaLogDestroy (IBaLog * pHdl, TBaBool saveCfg)
Destroy and release resources of logger.
Returns
True if success, otherwise, false
Parameters
in pHdl BaLog handle to destroy
in saveCfg Flag to specify if the state should be saved in a cfg file