BaProc.h File Reference
...
#include `BaBool.h`
*
Functions
Name of Processes
const char * BaProcGetOwnShortName ()
Get the short name of own process.
const char * BaProcGetOwnFullName ()
Get the full name of own process.
const char * BaProcGetPIDName (pid_t pid, char buf[BAPROC_SHORTNAMELEN])
Gets the process name from the PID.
Control TasK PID File
TBaBoolRC BaProcWriteCtrlTaskPidFile ()
Write/overwrite the Control Task PID file which is a special PID file.
pid_t BaProcReadCtrlTaskPidFile (char buf[BAPROC_SHORTNAMELEN])
Read the Control Task PID file.
TBaBoolRC BaProcDelCtrlTaskPidFile ()
Deletes the Control Task PID file.
PID Files
TBaBoolRC BaProcWriteOwnPidFile ()
Writes the PID file of an internal program.
pid_t BaProcReadPidFile (const char *progName, TBaBool internal)
Tries to read the PID from an internal program, or from a path.
TBaBoolRC BaProcDelPidFile (const char *progName, TBaBool internal)
Delete the PID file.
TBaBool BaProcPidFileIsRunning (const char *progName, TBaBool internal)
Test if a program with the PID inside the PID file is running and has the same name as progName.
Detailed Description
...
Function Documentation
const char* BaProcGetOwnShortName ()
Get the short name of own process.
Returns
on success, the process name, otherwise, 0
Referenced by BaProcWriteCtrlTaskPidFile(), and BaProcWriteOwnPidFile().
const char* BaProcGetOwnFullName ()
Get the full name of own process.
Returns
on success, the process name, otherwise, 0
Referenced by BaProcGetOwnShortName().
const char* BaProcGetPIDName (pid_t pid, char buf[BAPROC_SHORTNAMELEN])
Gets the process name from the PID.
If no buf is provided, the pointer is mallocated and has to be freed by the user to avoid memory leaks
Returns
on success, the process name, otherwise, 0
Parameters
in pid Process ID
out buf Optional buffer
TBaBoolRC BaProcWriteCtrlTaskPidFile ()
Write/overwrite the Control Task PID file which is a special PID file.
This function is meant to be called from within the forked control task.
Returns
Success or error
pid_t BaProcReadCtrlTaskPidFile (char buf[BAPROC_SHORTNAMELEN])
Read the Control Task PID file.
The special control task PID file contains name of the binary. This name is written to buf if the pointer is provided
Returns
The PID on success or 0 on error
Parameters
out buf Optional buffer to read the name of the binary
TBaBoolRC BaProcDelCtrlTaskPidFile ()
Deletes the Control Task PID file.
Returns
Success or error
TBaBoolRC BaProcWriteOwnPidFile ()
Writes the PID file of an internal program.
Returns
Success or error
pid_t BaProcReadPidFile (const char * progName, TBaBool internal)
Tries to read the PID from an internal program, or from a path.
Returns
on success, the PID, otherwise, 0
Parameters
in progName Internal program name or full path to PID file
in internal Flag to signal that the program was created with this API
Referenced by BaProcPidFileIsRunning().
TBaBoolRC BaProcDelPidFile (const char * progName, TBaBool internal)
Delete the PID file.
Returns
on success, the PID, otherwise, 0
Parameters
in progName Internal program name or full path to PID file
in internal Flag to signal that the program was created with this API
TBaBool BaProcPidFileIsRunning (const char * progName, TBaBool internal)
Test if a program with the PID inside the PID file is running and has the same name as progName.
Returns
true or false
Parameters
in progName Internal program name or full path to PID file
in internal Flag to signal that the program was created with this API