BaUtils.hpp File Reference
General useful functions
.
#include <sys/stat.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <dirent.h>
*
#include <string.h>
*
#include <stdarg.h>
*
#include <string>
*
#include <istream>
*
Namespaces
 BaFS
Namespace to wrap all file system functions.
 BaPath
Namespace to wrap all path functions.
Functions
template<typename T >
static T BaToNumber (std::string s, T def, bool *pError=0)
Converts string to number.
static std::string BaFString (const char *fmt,...)
Creates a string formated C-style with a maximum length of 65534 chars.
static std::string BaFString (const char *fmt, va_list arg)
Creates a string formated C-style with a maximum length of 65534 chars.
Base API File System
static int BaFS::MkDir (std::string dir, int per=0660)
Portable mkdir(), creates a directory.
static int BaFS::Rename (std::string path, std::string newPath)
Portable rename().
static uint32_t BaFS::Size (std::string path)
Gets the file size in bytes.
static uint64_t BaFS::DirSize (std::string path, uint32_t maxDepth=(uint32_t)-1)
Gets the directory size in bytes recursively with a maximum depth.
static bool BaFS::Exists (std::string path)
Tests if a file or directory exists.
Base API Path
static std::string BaPath::GetDirectory (std::string path, char delimiter= '/')
Gets everything, including the trailing path separator, except the filename.
static std::string BaPath::GetFilename (std::string path, char delimiter= '/')
Gets only the filename part of the path.
static std::string BaPath::GetFileExtension (std::string path, char delimiter= '/')
Gets the extension of a path.
static std::string BaPath::ChangeFileExtension (std::string path, std::string ext, char delimiter= '/')
Changes the extension of a path.
Detailed Description
General useful functions
.
Path functions
Number parsing
Function Documentation
template<typename T > static T BaToNumber (std::string s, T def, bool * pError = 0) [inline], [static]
Converts string to number.
Returns
Parsed number on success, otherwise def
Parameters
in s string
in def default to return if conversion fails
out pError Optional error flag
static std::string BaFString (const char * fmt, ...) [inline], [static]
Creates a string formated C-style with a maximum length of 65534 chars.
Returns
formated string
Parameters
in fmt format string
Referenced by BaLogSysLogF(), BaMsgSetLogF(), BaMsgSetPrintF(), and BaMsgSetSysLogF().
static std::string BaFString (const char * fmt, va_list arg) [inline], [static]
Creates a string formated C-style with a maximum length of 65534 chars.
Returns
formated string
Parameters
in fmt format string
in arg variable arguments