BaPath Namespace Reference
Namespace to wrap all path functions.
Functions
Base API Path
static std::string GetDirectory (std::string path, char delimiter= '/')
Gets everything, including the trailing path separator, except the filename.
static std::string GetFilename (std::string path, char delimiter= '/')
Gets only the filename part of the path.
static std::string GetFileExtension (std::string path, char delimiter= '/')
Gets the extension of a path.
static std::string ChangeFileExtension (std::string path, std::string ext, char delimiter= '/')
Changes the extension of a path.
Detailed Description
Namespace to wrap all path functions.
Function Documentation
static std::string BaPath::GetDirectory (std::string path, char delimiter = '/') [inline], [static]
Gets everything, including the trailing path separator, except the filename.
`/foo/bar/baz.txt` --> `/foo/bar/`
Returns
The directory part of the path (without filename)
Parameters
in path Full path
Referenced by ChangeFileExtension().
static std::string BaPath::GetFilename (std::string path, char delimiter = '/') [inline], [static]
Gets only the filename part of the path.
`/foo/bar/baz.txt` --> `baz.txt`
Returns
The filename including the extension
Parameters
in path Full path
Referenced by BaProcGetOwnFullName(), BaProcPidFileIsRunning(), ChangeFileExtension(), and GetFileExtension().
static std::string BaPath::GetFileExtension (std::string path, char delimiter = '/') [inline], [static]
Gets the extension of a path.
The period is considered part of the extension.
`/foo/bar/baz.txt` --> `.txt`
`/foo/bar/baz` --> ``
Returns
The extension
Parameters
in path Full path
static std::string BaPath::ChangeFileExtension (std::string path, std::string ext, char delimiter = '/') [inline], [static]
Changes the extension of a path.
The period is considered part of the extension.
`/foo/bar/baz.txt`, `.dat` --> `/foo/bar/baz.dat`
`/foo/bar/baz.txt`, `` --> `/foo/bar/baz`
`/foo/bar/baz`, `.txt` --> `/foo/bar/baz.txt`
Returns
The path with the new extension
Parameters
in path Full path
in ext Extension to replace
Referenced by BaProcDelPidFile(), BaProcReadPidFile(), and BaProcWriteOwnPidFile().