SET(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

SET(COMPILER_TRIPLE "aarch64-linux-gnu")

SET(CMAKE_C_COMPILER "clang-9")
SET(CMAKE_CXX_COMPILER "clang++-9")

include_directories(
   /usr/${COMPILER_TRIPLE}/include 
   /usr/${COMPILER_TRIPLE}/include/c++/7/${COMPILER_TRIPLE}
   )

SET(CROSS_COMPILER_FLAGS "--target=${COMPILER_TRIPLE}")
SET(CMAKE_CXX_FLAGS_INIT "${CROSS_COMPILER_FLAGS}")
SET(CMAKE_C_FLAGS_INIT "${CROSS_COMPILER_FLAGS}")

SET(CROSS_LINKER_FLAGS "-lpthread -v")
SET(CMAKE_EXE_LINKER_FLAGS_INIT "${CROSS_LINKER_FLAGS}")
SET(CMAKE_SHARED_LINKER_FLAGS_INIT "${CROSS_LINKER_FLAGS}")

# Search for programs only in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# Search for libraries and headers only in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

add_definitions(-DRPI)

